name: ci测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: 设置jdk环境
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#      - name: maven打包
#        run: mvn clean install
#      - name: 上传jar包和启动脚本到服务器中
#        run: sshpass -p ${{secrets.PASSWORD}} scp -r -o StrictHostKeyChecking=no ./target/citest-0.0.1-SNAPSHOT.jar ./Dockerfile root@${{secrets.HOST}}:/github/citest
  prod:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: ls -a via ssh
        run: ｜
          sshpass -v -p ${{secrets.PASSWORD}}  ssh -o StrictHostKeyChecking=no root@${{secrets.HOST}}
