name: ci测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置jdk环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven打包
        run: mvn clean install
      - name: 上传jar包和启动脚本到服务器中
        run: sshpass -p ${{secrets.PASSWORD}} scp -r -o StrictHostKeyChecking=no ./target/citest-0.0.1-SNAPSHOT.jar ./Dockerfile root@${{secrets.HOST}}:/github/citest
  prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 打包镜像
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            port: 22
            password: ${{secrets.PASSWORD}}
            script: cd /github/citest && docker build -t citest  .
      - name: 停止容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: 22
          password: ${{secrets.PASSWORD}}
          script:
            "if docker ps -a | grep -q 'citest';then
            docker stop citesst
            docker rm -f citest
            fi"
      - name: 创建容器
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          port: 22
          password: ${{secrets.PASSWORD}}
          script: docker run -d --name citest -p 8080:8080 citest
