name: ci测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置jdk环境
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven打包
        run: mvn clean install
      - name: 上传jar包和启动脚本到服务器中
        run: sshpass -p ${{secrets.PASSWORD}} scp -r -o StrictHostKeyChecking=no ./target/citest-0.0.1-SNAPSHOT.jar ./Dockerfile root@${{secrets.HOST}}:/github/citest
  prod:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 登录服务器
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 打包镜像
        run: |
            ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "
              cd /github/citest
              docker  build  -t citest:latest  . 
            "
