name: ci测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: upload file to ssh
        run: |
          ssh -vv $USERNAME@$HOST "mkdir -p $PROJECT_PATH"
          scp -vv target/*.jar $USERNAME@$HOST:$PROJECT_PATH
