name: ci测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "target/"
          REMOTE_HOST: 114.132.233.79
          REMOTE_PORT: 22
          REMOTE_USER: root
          TARGET: "/github/citest"
